### ISSUE TITLE
CUDA illegal memory access

### ISSUE THREAD

**Issue by neon5d** [shirgur/ACDRNet#2]
I ran train.py with building examples but I encountered the below error in neural_renderer.

alpha_map[face_index_map >= 0] = 1
RuntimeError: CUDA error: an illegal memory access was encountered

I installed the neural_render PyTorch version (1.1.3) successfully and tested all examples.
However, your train.py created CUDA illegal memory access.
Which neural_render version did you use?
Do you have any suggestions to resolve this issue?

Thank youi

**Comment by shirgur** [comment]
Please try this version of the neural renderer
```
git clone --branch at_assert_fix --single-branch https://github.com/daniilidis-group/neural_renderer.git
cd neural_renderer
python setup.py install
```

You can also try and work with any renderer that output silhouettes, and compatible with your PyTorch version

**Comment by neon5d** [comment]
Thank you for your response.
I found the issue is that neural_renderer does not support multigpu environment. Only the first GPU can be used without any issue.
