### ISSUE TITLE
Pytorch version issue ?

### ISSUE THREAD

**Issue by neon5d** [shirgur/ACDRNet#3]
I am not sure this is related to the Pytorch version.
Currently, I am using Pytorch 1.4.
There are two issues.
1. iou_ac = get_iou(pred_mask_ac.gt(0.2), mask.byte())
mask.byte() is not bool, so & operation occurs an error.
After I changed iou_ac = get_iou(pred_mask_ac.gt(0.2), **mask.bool()**), It looks ok.

def get_iou(outputs, labels):
    outputs = outputs.squeeze(1)
    intersection = (**outputs & labels**).float().sum((1, 2)) => error occurs

2.  def get_ap_scores(predict, target, ignore_index=-1):
    ap = []
    for pred, tgt in zip(predict, target):
        # Tensor process
        pred = pred.data.cpu().numpy().reshape(-1)
        tgt = tgt.data.cpu().numpy().reshape(-1)
        p = pred[tgt != ignore_index]
        t = tgt[tgt != ignore_index]
        ap.append(average_precision_score(t, p) => error
 I changed it into ap.append(average_precision_score(t, p, **pos_label=0)**)

**Comment by shirgur** [comment]
As mentioned in the "Prerequisites", this version currently supports PyTorch 1.1
